/*
* Ejercicio 1.
* Implementar una solución para el problema del barbero durmiente. El problema consiste en una barbería donde 
* trabaja un barbero, se cuenta con un sillón para cortar el pelo y varias sillas para esperar 
* (supongamos que son 5). Cuando no tiene clientes el barbero se duerme. Al llegar un cliente si el barbero está 
* durmiendo lo despierta y ocupa la sillón para cortarse el pelo. Si llega un nuevo cliente y el barbero está ocupado, 
* se sienta si existe una silla libre; en caso contrario se va de la barbería. 
*
* El programa debe satisfacer:
*
*    la exclusión mutua (el sillón y el barbero estarán con el mismo cliente).
*    evitar el interbloqueo (que no se atiendan más clientes).
*    evitar la inanición (todos los clientes serán atendidos).
*
* Mejoras propuestas para el ejercicio:
* 
*    Incorporar a la aplicación una interfaz gráfica.
*    Visualizar de forma gráfica el estado de la barbería.
*/

package barberodormilon;

import javax.swing.JOptionPane;

/**
 *
 * @author pabloaparicioestevez
 */
public class Barberia_grafico extends javax.swing.JFrame {

    /**
     * Creates new form Barberia_grafico
     */
    public Barberia_grafico() {
        //Iniciamos los componentes de la aplicacion grafica
        initComponents();
        //ponemos todos los muñecos ocultos al iniciar el programa menos el barbero dormido
        Barberia_grafico.hombre1label.setVisible(false);
        Barberia_grafico.hombre2label.setVisible(false);
        Barberia_grafico.hombre3label.setVisible(false);
        Barberia_grafico.hombre4label.setVisible(false);
        Barberia_grafico.hombre5label.setVisible(false);
        Barberia_grafico.hombreatendidolabel.setVisible(false);
        Barberia_grafico.dormido.setVisible(true);
        Barberia_grafico.salirLabel.setVisible(false);
        
        //Mostramos el numero de clientes en el contador del entorno gráfico
        Barberia_grafico.contadorLabel.setText(Integer.toString(Barberia.numClientes));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        silla1label = new javax.swing.JLabel();
        silla2label = new javax.swing.JLabel();
        silla3label = new javax.swing.JLabel();
        silla4label = new javax.swing.JLabel();
        silla5label = new javax.swing.JLabel();
        hombre1label = new javax.swing.JLabel();
        hombre2label = new javax.swing.JLabel();
        hombre3label = new javax.swing.JLabel();
        hombre4label = new javax.swing.JLabel();
        hombre5label = new javax.swing.JLabel();
        sillabarberolabel = new javax.swing.JLabel();
        hombreatendidolabel = new javax.swing.JLabel();
        dormido = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea1 = new javax.swing.JTextArea();
        tituloLabel = new javax.swing.JLabel();
        salirLabel = new javax.swing.JLabel();
        iniciarButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        reiniciarButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        iconrightLabel = new javax.swing.JLabel();
        iconleftLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        contadorLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SalirMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        acercaMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        silla1label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/silla.png"))); // NOI18N

        silla2label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/silla.png"))); // NOI18N
        silla2label.setText("jLabel1");

        silla3label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/silla.png"))); // NOI18N
        silla3label.setText("jLabel2");

        silla4label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/silla.png"))); // NOI18N
        silla4label.setText("jLabel3");

        silla5label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/silla.png"))); // NOI18N
        silla5label.setText("jLabel4");

        hombre1label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/hombre.png"))); // NOI18N
        hombre1label.setText("jLabel2");

        hombre2label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/hombre.png"))); // NOI18N
        hombre2label.setText("jLabel1");

        hombre3label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/hombre.png"))); // NOI18N
        hombre3label.setText("jLabel3");

        hombre4label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/hombre.png"))); // NOI18N
        hombre4label.setText("jLabel4");

        hombre5label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/hombre.png"))); // NOI18N
        hombre5label.setText("jLabel5");

        sillabarberolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/sillaBarbero.png"))); // NOI18N
        sillabarberolabel.setText("jLabel1");

        hombreatendidolabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/hombre.png"))); // NOI18N
        hombreatendidolabel.setText("jLabel1");

        dormido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/dormido.png"))); // NOI18N
        dormido.setText("jLabel2");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Log:"));

        logTextArea1.setColumns(20);
        logTextArea1.setRows(5);
        jScrollPane1.setViewportView(logTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tituloLabel.setFont(new java.awt.Font("You're Gone", 0, 48)); // NOI18N
        tituloLabel.setText("Barbero dormilón");

        salirLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/salida.png"))); // NOI18N
        salirLabel.setText("No hay sillas, cliente se va");

        iniciarButton.setText("Iniciar");
        iniciarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciarButtonMouseClicked(evt);
            }
        });
        iniciarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarButtonActionPerformed(evt);
            }
        });

        salirButton.setText("Salir");
        salirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirButtonMouseClicked(evt);
            }
        });

        reiniciarButton.setText("Reiniciar");
        reiniciarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reiniciarButtonMouseClicked(evt);
            }
        });
        reiniciarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarButtonActionPerformed(evt);
            }
        });

        iconrightLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconobarberoRight.png"))); // NOI18N
        iconrightLabel.setText("jLabel1");

        iconleftLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconobarberoLeft.png"))); // NOI18N
        iconleftLabel.setText("jLabel2");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Clientes restantes:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 13))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(contadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        SalirMenu.setText("Salir");
        SalirMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMenuMouseClicked(evt);
            }
        });
        jMenu1.add(SalirMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        acercaMenu.setText("Acerca de...");
        acercaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acercaMenuMouseClicked(evt);
            }
        });
        jMenu2.add(acercaMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(hombreatendidolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(sillabarberolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dormido, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(salirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(37, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(hombre1label, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(hombre2label, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(hombre3label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(silla1label, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(silla2label, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(silla3label, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(silla4label, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(silla5label, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(hombre4label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(hombre5label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iniciarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(reiniciarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconleftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(tituloLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconrightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(iconrightLabel)
                                .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(iconleftLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iniciarButton)
                            .addComponent(salirButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reiniciarButton)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sillabarberolabel)
                            .addComponent(hombreatendidolabel)
                            .addComponent(dormido)
                            .addComponent(salirLabel))
                        .addGap(65, 65, 65)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(hombre3label)
                                            .addComponent(hombre4label)
                                            .addComponent(hombre5label)
                                            .addComponent(hombre2label))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(silla2label, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(silla3label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(silla4label, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(silla5label)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hombre1label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(silla1label, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirButtonMouseClicked
        //boton para salir del programa
        System.exit(0);
    }//GEN-LAST:event_salirButtonMouseClicked

    private void iniciarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarButtonMouseClicked
        //creamos  hilo barberia 
        Barberia barberia=new Barberia();
        //Creamos hilos cliente y barbero
        Barbero barbero=new Barbero(barberia); 
        Cliente cliente=new Cliente(barberia);   
        
        //se crea el hilo para las excepciones
       ManejadorExcepciones manejador=new ManejadorExcepciones();
       //se crea el manejador
       cliente.setUncaughtExceptionHandler(manejador);
       barbero.setUncaughtExceptionHandler(manejador);

        
        //iniciamos los hilos
        barbero.start();
        cliente.start();

    }//GEN-LAST:event_iniciarButtonMouseClicked

    private void reiniciarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reiniciarButtonMouseClicked
        //reseteamos el contador de sillas ocupadas
        Barberia.sillasOcupadas=0;
        //borramos el textarea para el LOG
        logTextArea1.setText("");
        //llamamos al metodo para visualizar los muñecos
        Barberia.sillasVisibles();
        //reseteamos el contador de numero de clientes a atender, por defecto es 20
        Barberia.numClientes=20;
    }//GEN-LAST:event_reiniciarButtonMouseClicked

    private void reiniciarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reiniciarButtonActionPerformed

    private void SalirMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMenuMouseClicked
                //boton para salir del programa
        System.exit(0);
    }//GEN-LAST:event_SalirMenuMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void acercaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acercaMenuMouseClicked
        JOptionPane.showMessageDialog(null,"Creado por Pablo Aparicio Estévez en noviembre del 2016 -DAM-IES Aguadulce"); 
    }//GEN-LAST:event_acercaMenuMouseClicked

    private void iniciarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barberia_grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barberia_grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barberia_grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barberia_grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         //creamos la barberia


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //iniciamos el entorno grafico
                new Barberia_grafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu SalirMenu;
    private javax.swing.JMenu acercaMenu;
    public static javax.swing.JLabel contadorLabel;
    public static javax.swing.JLabel dormido;
    public static javax.swing.JLabel hombre1label;
    public static javax.swing.JLabel hombre2label;
    public static javax.swing.JLabel hombre3label;
    public static javax.swing.JLabel hombre4label;
    public static javax.swing.JLabel hombre5label;
    public static javax.swing.JLabel hombreatendidolabel;
    private javax.swing.JLabel iconleftLabel;
    private javax.swing.JLabel iconrightLabel;
    private javax.swing.JButton iniciarButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextArea logTextArea1;
    private javax.swing.JButton reiniciarButton;
    private javax.swing.JButton salirButton;
    public static javax.swing.JLabel salirLabel;
    private javax.swing.JLabel silla1label;
    private javax.swing.JLabel silla2label;
    private javax.swing.JLabel silla3label;
    private javax.swing.JLabel silla4label;
    private javax.swing.JLabel silla5label;
    private javax.swing.JLabel sillabarberolabel;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
